version: '3'

services:
  db:
    image: postgres
    ports:
    - 6543:5432
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  web:
    build: .
    image: concourse/concourse:local
    volumes:
    - .:/src
    command: web
    depends_on: [db]
    ports:
    - 8080:8080
    environment:
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_CLUSTER_NAME: dev
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: random
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_TRACING_JAEGER_COMPONENT: atc
      CONCOURSE_TRACING_JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  worker: &worker-config
    build: .
    image: concourse/concourse:local
    command: worker
    privileged: true
    depends_on: [web]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_BIND_IP: 0.0.0.0
  worker2: *worker-config
  worker3: *worker-config

  jaeger:
    image: jaegertracing/all-in-one:1.14
    command:
      - --sampling.strategies-file=/etc/jaeger/sampling_strategies.json
      - --log-level=debug
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '14268:14268'
      - '25000:16686'
      - '5775:5775/udp'
      - '5778:5778'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '9411:9411'
