resource_types:
- name: concourse-pipeline
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: fork
  type: git
  source:
    uri: https://((github-token))@github.com/cirocosta/concourse
    branch: master

- name: maintenance-branch
  type: git
  source:
    uri: https://((github-token))@github.com/cirocosta/concourse
    branch: maintenance

- name: upstream
  type: git
  source:
    uri: https://github.com/concourse/concourse
    branch: master

- name: pipelines
  type: concourse-pipeline
  source:
    target: https://hush-house.concourse-ci.org
    teams:
    - name: main
      username: admin
      password: ((admin-password))


jobs:
- name: bump-fork
  plan:
  - get: upstream
    trigger: true
  - put: fork
    inputs: [ upstream ]
    params:
      repository: ./upstream

- name: set-pipelines
  plan:
  - get: maintenance-branch
    trigger: true
    passed: [ generate-pipelines ]
  - put: pipelines
    params:
      pipelines:
      - name: build-branches
        team: main
        config_file: ./maintenance-branch/ci/build-branches.yml


- name: generate-pipelines
  plan:
  - get: maintenance-branch
    trigger: true
  - task: generate
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      inputs:
      - name: maintenance-branch
      caches:
      - path: ./jsonnet
      run:
        path: /bin/sh
        args:
        - -c
        - -e
        - |
          export PATH=$PATH:$(realpath ./jsonnet)

          apk add --update make jq git libstdc++

          if [ ! -x "$(command -v jsonnet)" ]; then
            apk add g++
            git clone https://github.com/google/jsonnet ./jsonnet
            make -C ./jsonnet -j6
          fi

          cd ./maintenance-branch
          make

          if [ ! -z "$(git status --porcelain)" ]; then
            git config user.name "Ciro S. Costa"
            git config user.email "cscosta@pivotal.io"
            git add --all
            git commit -m "[maintenance] bump"
          fi

  - put: maintenance-branch
    params:
      repository: ./maintenance-branch
